export default {
    giftTableHead: [
			{ title: '序号', dataIndex: 'serialNum', key: 'serialNum',},
			{ title: '订单编号', dataIndex: 'orderNo', key: 'orderNo' },
			{ title: '下单时间', dataIndex: 'createTime', key: 'createTime'},
			{ title: '下单门店名称', dataIndex: 'storeName', key: 'storeName'},
			{ title: '关联销售出库单编号', dataIndex: 'leaveWarehouseNo', key: 'leaveWarehouseNo'},
			{ title: '销售员/收银员', dataIndex: 'createEmployeeName', key: 'createEmployeeName' },
			{ title: '扣减积分', dataIndex: 'totalAmount', key: 'totalAmount'},
			{ title: '订单来源', dataIndex: 'type', key: 'type'},
			{ title: '订单状态', dataIndex: 'changeTradeStatus', key: 'changeTradeStatus'},
			{ title: '操作', dataIndex: 'actions', key: 'actions', width: 200},
		],
		baseTableHead: [
			{ title: '订单状态', dataIndex: 'changeTradeStatus', key: 'changeTradeStatus',},
			{ title: '订单编号', dataIndex: 'orderNo', key: 'orderNo' },
			{ title: '下单时间', dataIndex: 'createTime', key: 'createTime'},
			{ title: '订单来源', dataIndex: 'type', key: 'type'},
			{ title: '下单门店', dataIndex: 'storeName', key: 'storeName'},
			{ title: '销售员/收银员', dataIndex: 'createEmployeeName', key: 'createEmployeeName'},
			{ title: '实付金额', dataIndex: 'totalAmount', key: 'totalAmount' },
			{ title: '获取积分', dataIndex: 'totalReturnIntegral', key: 'totalReturnIntegral'},
			{ title: '购买数量', dataIndex: 'buyCount', key: 'buyCount' },
		],
		giftsTableHead: [
			{ title: '序号', dataIndex: 'serialNum', key: 'serialNum',},
			{ title: '商品名称', dataIndex: 'goodsName', key: 'goodsName' },
			{ title: '商品编号', dataIndex: 'goodsHrNo', key: 'goodsHrNo'},
			{ title: '单位', dataIndex: 'priceUnitName', key: 'priceUnitName'},
			{ title: '单价(元)', dataIndex: 'unitPrice', key: 'unitPrice'},
			{ title: '数量', dataIndex: 'goodsNum', key: 'goodsNum'},
			{ title: '获取积分', dataIndex: 'returnIntegral', key: 'returnIntegral' },
			{ title: '应付金额(元)', dataIndex: 'subtotal', key: 'subtotal'},
			{ title: '是否有赠品', dataIndex: 'isGift', key: 'isGift' },
			{ title: '备注', dataIndex: 'remark', key: 'province' },
		],
		memberTableHead: [
			{ title: '会员姓名', dataIndex: 'name', key: 'name',},
			{ title: '手机号', dataIndex: 'mobile', key: 'mobile' },
			{ title: '会员卡号', dataIndex: 'cardNo', key: 'cardNo'},
			{ title: '地址', dataIndex: 'address', key: 'address'},
			{ title: '会员注册门店', dataIndex: 'storeName', key: 'storeName'},
			{ title: '会员积分', dataIndex: 'nowIntegral', key: 'nowIntegral'},
			{ title: '会员等级', dataIndex: 'province', key: 'province' },
		],
		operateTableHead: [
			{ title: '操作人', dataIndex: 'serialNum', key: 'serialNum',},
			{ title: '时间', dataIndex: 'k3Code', key: 'code' },
			{ title: '操作类别', dataIndex: 'depotName', key: 'storeName'},
			{ title: '操作日志', dataIndex: 'belongCompanyName', key: 'belongCompanyName'},
		]
}
