export default [
  {title: '序号', dataIndex: 'serialNumber', width: 80},
  {title: '货品', dataIndex: 'productProperty', width: 300},
  {title: '货品图片', dataIndex: 'mainImgs', visible: 1},
  {title: '货品名称', dataIndex: 'name', formType: 'input', visible: 1},
  {title: '货品编号', dataIndex: 'k3No', formType: 'input', visible: 1},
  {title: '货品条码', dataIndex: 'barCode', visible: 1},
  {title: '包装规格', dataIndex: 'packingSpec'},
  {title: '库存单位', dataIndex: 'goodsStockUnit'},
  {title: '计价单位', dataIndex: 'goodsPriceUnit'},
  {title: '货品类别', dataIndex: 'goodsTypeList', formType: 'select'},
  {title: '货品分类', dataIndex: 'categoriesName', formType: 'cascader'},
  {title: '销售价格', dataIndex: 'realPrice'},
  {title: '会员价格', dataIndex: 'realUserPrice'},
  {title: '兑换积分', dataIndex: 'integral'},
  // {title: '上下架状态', dataIndex: 'isPutOn'},
]