export default [
    { title: '序号', dataIndex: 'serialNum', key: 'serialNum',},
    { title: 'K3编码', dataIndex: 'k3Code', key: 'code' },
    { title: '仓库名称', dataIndex: 'depotName', key: 'storeName'},
    { title: '所属公司', dataIndex: 'belongCompanyName', key: 'belongCompanyName'},
    { title: '所属门店', dataIndex: 'companyOrStoreName', key: 'companyOrStoreName'},
    { title: '仓库编号', dataIndex: 'depotCode', key: 'storeNumber'},
    { title: '所属省', dataIndex: 'province', key: 'province' },
    { title: '所属市', dataIndex: 'city', key: 'city'},
    { title: '所属区', dataIndex: 'region', key: 'area'},
    { title: '详细地址', dataIndex: 'adress', key: 'detailAddress', width: '8%'},
    { title: '负责人', dataIndex: 'userName', key: 'principal'},
    { title: '联系方式', dataIndex: 'phone', key: 'tel'},
    { title: '状态', dataIndex: 'newStatus', key: 'newStatus'},
    { title: '允许货架管理', dataIndex: 'allowShelfMana', key: 'allowShelfManag'},
    { title: '允许负库存', dataIndex: 'allowNegStock', key: 'allowNegStore'},
    { title: '参与预警', dataIndex: 'allowWarn', key: 'warning'},
    { title: '备注', dataIndex: 'remark', key: 'backup'},
    { title: '操作', dataIndex: 'actions', key: 'actions', width: 250},
]
